version: '3.8'

services:
  keydb:
    image: eqalpha/keydb
    container_name: textoria-keydb
    ports:
      - "6379:6379"
    command: keydb-server /etc/keydb/keydb.conf --server-threads 4 --requirepass password

  postgres:
    image: postgres:13
    container_name: textoria-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=textoria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    container_name: textoria-back
    environment:
        - KEYDB_URI=$KEYDB_URI
        - DATABASE_URL=postgres://postgres:password@postgres:5432/textoria
    ports:
      - "8000:8000"
    build: .
    depends_on:
      - postgres
      - keydb

  front:
    container_name: textoria-front
    build: https://github.com/textoria/frontend.git
    environment:
      - BACKEND_URL=http://back:8000
    ports:
      - '3000:3000'
    depends_on:
      - back

volumes:
  postgres_data:
